p8105_hw6_amz2148
================

Data Science: Homework 3

# Problem 0

``` r
library(tidyverse) #loads tidyverse package
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.3      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(purrr) #loads purrr package
library(patchwork) #loads patchwork package
set.seed(1) #sets seed for reproducibility 
```

``` r
knitr::opts_chunk$set(echo = TRUE) #shows all code chunks
knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = 1,
  out.width = "100%") #sets figure dimensions

theme_set(theme_minimal() + theme(legend.position = "bottom")) #sets default figure theme
```

# Problem 1

# Problem 2

First we import the `homicides` dataset from the Washington Post
(originally called `homicide_data.csv`). We also change all unknown
values to NA for consistency as some (but not all) variables are already
coded this way.

``` r
homicides = 
  read_csv("data/homicide_data.csv") %>% #loads csv file
  janitor::clean_names() %>% #cleans variable names
  gdata::unknownToNA("Unknown", warning = FALSE) #changes all "unknown" values to "NA"
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Next, we create a `city_state` variable (e.g. “Baltimore, MD”) and a
binary `status` variable indicating whether the homicide is solved. We
omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t
report victim race. We also omit Tulsa, AL – this is a data entry
mistake. For this problem, we limit our analysis to those for whom
`victim_race` is white or black. We also convert `victim_age` to numeric
form.

``` r
homicides = 
  homicides %>% 
  mutate(state = replace(state, state == "wI", "WI")) %>% #fixes values erroneously labeled wI
  mutate(city_state = paste(city, state, sep = ", ")) %>% #creates city_state variable
  mutate(status = case_when(disposition == "Closed without arrest" | disposition == "Open/No arrest" ~ "Unresolved", disposition == "Closed by arrest" ~ "Resolved")) %>% #creates binary status variable
  filter(city_state != "Dallas, TX", city_state != "Phoenix, AZ", city_state != "Kansas City, MO", city_state != "Tulsa, AL") %>% #omits specified cities
  filter(victim_race == "White" | victim_race == "Black") %>% #limits analyses to only White and Black victims
mutate(
    statusdbl = as.numeric(status == "Resolved"), #creates numeric, binary status variable where resolved = 1, unresolved = 0
    victim_age = as.numeric(victim_age), #reclassifies age as numeric variable
    victim_racedbl = as.numeric(victim_race == "White"), #creates numeric race variable where White = 1, Black = 0
    victim_sexdbl = as.numeric(victim_sex == "Female")) #creates numeric sex variable where Female = 1, Male = 0

head(homicides) #outputs first few rows of dataset
```

    ## # A tibble: 6 × 17
    ##   uid    repor…¹ victi…² victi…³ victi…⁴ victi…⁵ victi…⁶ city  state   lat   lon
    ##   <chr>    <dbl> <chr>   <chr>   <chr>     <dbl> <chr>   <chr> <chr> <dbl> <dbl>
    ## 1 Alb-0…  2.01e7 SATTER… VIVIANA White        15 Female  Albu… NM     35.1 -107.
    ## 2 Alb-0…  2.01e7 MULA    VIVIAN  White        72 Female  Albu… NM     35.1 -107.
    ## 3 Alb-0…  2.01e7 BOOK    GERALD… White        91 Female  Albu… NM     35.2 -107.
    ## 4 Alb-0…  2.01e7 MARTIN… GUSTAVO White        56 Male    Albu… NM     35.1 -107.
    ## 5 Alb-0…  2.01e7 LUJAN   KEVIN   White        NA Male    Albu… NM     35.1 -107.
    ## 6 Alb-0…  2.01e7 GRAY    STEFAN… White        43 Female  Albu… NM     35.1 -107.
    ## # … with 6 more variables: disposition <chr>, city_state <chr>, status <chr>,
    ## #   statusdbl <dbl>, victim_racedbl <dbl>, victim_sexdbl <dbl>, and abbreviated
    ## #   variable names ¹​reported_date, ²​victim_last, ³​victim_first, ⁴​victim_race,
    ## #   ⁵​victim_age, ⁶​victim_sex

For the city of Baltimore, MD, we use the `glm` function to fit a
logistic regression with resolved vs unresolved as the outcome and
victim age, sex and race as predictors. We save the output of `glm` as
an R object; apply `broom::tidy` to this object; and obtain the estimate
and confidence interval of the adjusted odds ratio for solving homicides
comparing male victims to female victims, keeping all other variables
fixed.

``` r
baltimore_logistic = 
  homicides %>% 
  filter(city_state == "Baltimore, MD") %>% #restricts dataset to Baltimore, MD
  glm(statusdbl ~ victim_age + victim_sexdbl + victim_racedbl, data = ., family = binomial()) #runs logistic regression with outcome of status and covariates of age, sex, and race

baltimore_OR = 
  baltimore_logistic %>% 
  broom::tidy(conf.int = TRUE) %>% #tidies regression output into dataframe, adds ln confidence intervals
  janitor::clean_names() %>% #cleans variable names
  mutate(
    OR = exp(estimate),
    conf_low = exp(conf_low),
    conf_high = exp(conf_high)) %>% #creates OR variable and exponentiated CIs
  select(term, OR, conf_low, conf_high) %>% #selects only specified variables
  filter(term == "victim_sexdbl") %>% #keeps only results for victim_sex variable
  knitr::kable(digits = 3) #creates table with resulting data

baltimore_OR #outputs table
```

| term          |   OR | conf_low | conf_high |
|:--------------|-----:|---------:|----------:|
| victim_sexdbl | 2.35 |    1.794 |     3.085 |

As the above table demonstrates, the estimated odds ratio comparing the
odds of having a resolved homicide (as opposed to unresolved) in Black
or White females from Baltimore, MD was 2.35 times the odds of having a
resolved homicide in Black or White males from Baltimore, MD - holding
victim age and race constant. We are 95% confident that the true odds
ratio comparing resolved status in Black and White females vs. males in
Baltimore, MD for this time period lies between 1.794 and 3.085.

Now, we run `glm` for each of the cities in the `homicides` dataset, and
extract the adjusted odds ratio and CI for solving homicides comparing
male victims to female victims. We do this within a “tidy” pipeline,
making use of `purrr::map`, list columns, and `unnest` as necessary to
create a dataframe with estimated ORs and CIs for each city.

``` r
all_cities = 
  homicides %>% 
  select(city_state, everything()) %>%
  nest(data = uid:victim_sexdbl) %>%
  mutate(log_model = map(data, ~ glm(statusdbl ~ victim_age + victim_sexdbl + victim_racedbl, data = ., family = binomial()))) %>% #runs logistic regression with outcome of status and covariates of age, sex, and race
  mutate(model_info = map(log_model, broom::tidy, conf.int = TRUE)) %>%
  select(city_state, model_info) %>%
  unnest(cols = model_info) %>% 
  janitor::clean_names() %>% #cleans variable names
  mutate(
    OR = exp(estimate),
    conf_low = exp(conf_low),
    conf_high = exp(conf_high)) %>% #creates OR variable and exponentiated CIs
  select(city_state, term, OR, conf_low, conf_high) %>% #selects only specified variables
  filter(term == "victim_sexdbl") %>% #keeps only results for victim_sex
  mutate(city_state = reorder(city_state, -OR)) #reorders city_state variables in order of descending ORs
  
head(all_cities)
```

    ## # A tibble: 6 × 5
    ##   city_state      term             OR conf_low conf_high
    ##   <fct>           <chr>         <dbl>    <dbl>     <dbl>
    ## 1 Albuquerque, NM victim_sexdbl 0.566    0.266      1.21
    ## 2 Atlanta, GA     victim_sexdbl 1.00     0.686      1.47
    ## 3 Baltimore, MD   victim_sexdbl 2.35     1.79       3.08
    ## 4 Baton Rouge, LA victim_sexdbl 2.62     1.46       4.89
    ## 5 Birmingham, AL  victim_sexdbl 1.15     0.761      1.75
    ## 6 Boston, MA      victim_sexdbl 1.50     0.794      2.85

Finally, we create a plot that shows the estimated ORs and CIs for each
city organized according to estimated OR.

``` r
ggplot(all_cities, aes( x = city_state, y = OR)) + #creates ggplot of city_state vs. proportion of unsolved homicides
  geom_bar(stat = 'identity', alpha = 0.7, fill = "#d98fcc") + #creates bar-chart
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high), alpha = 0.7) +  #adds error-bars
  theme(plot.title = element_text(size = 12, face = "bold")) + #edits title size
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 10)) + #edits appearance of x axis labels
  theme(axis.text.y = element_text(size = 10)) + #edits y axis label size
  theme(axis.title = element_text(size = 10, face = "bold")) + #edits axes title sizes
  theme(plot.caption = element_text(size = 8)) + #edits caption size
  labs(
      title = "Odds ratios for solved homicides in female vs. male victims",
      x = "City, State",
      y = "Odds Ratio",
      caption = "Data from Washington Post. Odds ratios are adjusted for race (Black or White) and age of victim. Error bars show 95% confidence intervals.") #adds figure title, axes titles, and caption
```

<img src="p8105_hw6_amz2148_files/figure-gfm/OR_plot-1.png" width="100%" />

The resulting plot shows that New York, NY has the highest OR of solved
homicides in female vs. male victims, controlling for age and race. This
means that in New York, female victims have the greatest odds when
compared to those of males for having a solved homicide. The ORs are
highly variable across U.S. cities, with most having ORs greater than 1,
but some having ORs less than 1 (which means in these latter cities,
male victims have a higher odds of having a solved homicide compared to
females). The confidence intervals, however, of many of these estimates
are quite large. Furthermore many include the null value of 1, which
means that in tose cities, there is no statistically significant
difference between odds of having a solved homicide in female vs. male
victims.

# Problem 3

First, we load and clean the `birthweight.csv` data for regression
analysis (i.e., convert numeric to factor variables where appropriate,
check for missing data, etc.).

``` r
birthweight = 
  read_csv("data/birthweight.csv") %>% #loads csv file
  janitor::clean_names() #cleans variable names
```

    ## Rows: 4342 Columns: 20
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (20): babysex, bhead, blength, bwt, delwt, fincome, frace, gaweeks, malf...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
